common:
    lid_topic:  "/points_raw"
    imu_topic:  "/imu_raw"
    
preprocess:
    lidar_type: 2                # VLP-16 LiDAR
    scan_line: 32
    blind: 4

mapping:
    acc_cov: 1
    gyr_cov: 1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    extrinsic_T: [ 0, 0, 0] #ULHK   #[ -0.5, 1.4, 1.5 ] #utbm
    extrinsic_R: [ 1, 0, 0, 
                   0, 1, 0,
                   0, 0, 1]
